### ISSUE TITLE
[Bug]: SSL email not sending

### ISSUE THREAD

**Issue by MichalNemec** [ThexXTURBOXx/catcher_2#14]
### Description

Trying to send an crash email is not working. It worked in original catcher

### Minimal Reproduction

Steps to reproduce the behaviour:

1. Use the following code:
    ```dart
    Catcher2Options releaseOptions = Catcher2Options(
    //SilentReportMode(),
    DialogReportMode(),
    [
      EmailAutoHandler(
        'mail.domain.com',
        587,
        Endpoints.mailerApp, //Sender email
        'xxx app', //Sender name
        'xxxx', //sender password
        [Endpoints.errorAppEmail],
        sendHtml: true,
        emailTitle: Endpoints.emailBugSubject,
        emailHeader: 'Exception on xxx app',
        enableStackTrace: true,
        printLogs: true,
        enableSsl: true,
      ),
    ],
    )
    ```

2. throw exception

### Exception or Error

```
2023-11-05 18:37:48.552 32666-32715 flutter                 com.example.app                     I  [2023-11-05 18:37:48.552384 | Catcher 2 | INFO] Setup localization lazily!
2023-11-05 18:37:54.191 32666-32715 flutter                 com.example.app                     I  [2023-11-05 18:37:54.190950 | Catcher 2 | INFO] Sending email...
2023-11-05 18:37:54.191 32666-32715 flutter                 com.example.app                     I  [2023-11-05 18:37:54.191218 | Connection | FINER] Connecting to mail.xxx.com at port 587.
2023-11-05 18:37:54.336 32666-32715 flutter                 com.example.app                     I  [2023-11-05 18:37:54.336104 | Catcher 2 | INFO] HandshakeException: Handshake error in client (OS Error: 
                                                                                                    	WRONG_VERSION_NUMBER(tls_record.cc:231))
2023-11-05 18:37:54.336 32666-32715 flutter                 com.example.app                     I  [2023-11-05 18:37:54.336649 | Catcher 2 | INFO] #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
                                                                                                    #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142)
                                                                                                    #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:918)
                                                                                                    #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1047)
                                                                                                    <asynchronous suspension>
2023-11-05 18:37:54.336 32666-32715 flutter                 com.example.app                     I  [2023-11-05 18:37:54.336789 | Catcher 2 | INFO] Report result: false
2023-11-05 18:37:54.336 32666-32715 flutter                 com.example.app                     I  [2023-11-05 18:37:54.336901 | Catcher 2 | WARNING] Instance of 'EmailAutoHandler' failed to report error
```

### Expected Behaviour

mail is sent successfully.

### Device

Samsung S22

### OS

Android 13

### Flutter version

3.13.6

### catcher_2 version

1.0.4

### Checklist

- [X] I have read and followed the **entire** [README](https://github.com/ThexXTURBOXx/catcher_2/blob/master/README.md) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by MichalNemec** [comment]
wrong port, whoops
